use thp_diagnostics::Span;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TokenKind {
    OpenTag,
    Identifier,
    Variable,
    Integer,
    Float,
    String,
    Function,
    Namespace,
    Class,
    Interface,
    Trait,
    Use,
    Const,
    InsteadOf,
    Implements,
    Extends,
    Abstract,
    Final,
    Public,
    Protected,
    Private,
    Static,
    New,
    InstanceOf,
    Throw,
    Try,
    Catch,
    Finally,
    Using,
    Return,
    If,
    ElseIf,
    Else,
    While,
    For,
    Foreach,
    As,
    Break,
    Continue,
    Match,
    Default,
    Echo,
    True,
    False,
    Null,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Colon,
    Semicolon,
    Comma,
    Question,
    QuestionQuestion,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Dot,
    Ellipsis,
    Equal,
    EqualEqual,
    StrictEqual,
    StrictNotEqual,
    Bang,
    BangEqual,
    AndAnd,
    OrOr,
    Pipe,
    FatArrow,
    Arrow,
    DoubleColon,
    NamespaceSeparator,
    Eof,
}

impl TokenKind {
    pub const fn description(self) -> &'static str {
        match self {
            Self::OpenTag => "`<?thp`",
            Self::Identifier => "identifier",
            Self::Variable => "variable",
            Self::Integer => "integer",
            Self::Float => "float",
            Self::String => "string",
            Self::Function => "`function`",
            Self::Namespace => "`namespace`",
            Self::Class => "`class`",
            Self::Interface => "`interface`",
            Self::Trait => "`trait`",
            Self::Use => "`use`",
            Self::Const => "`const`",
            Self::InsteadOf => "`insteadof`",
            Self::Implements => "`implements`",
            Self::Extends => "`extends`",
            Self::Abstract => "`abstract`",
            Self::Final => "`final`",
            Self::Public => "`public`",
            Self::Protected => "`protected`",
            Self::Private => "`private`",
            Self::Static => "`static`",
            Self::New => "`new`",
            Self::InstanceOf => "`instanceof`",
            Self::Throw => "`throw`",
            Self::Try => "`try`",
            Self::Catch => "`catch`",
            Self::Finally => "`finally`",
            Self::Using => "`using`",
            Self::Return => "`return`",
            Self::If => "`if`",
            Self::ElseIf => "`elseif`",
            Self::Else => "`else`",
            Self::While => "`while`",
            Self::For => "`for`",
            Self::Foreach => "`foreach`",
            Self::As => "`as`",
            Self::Break => "`break`",
            Self::Continue => "`continue`",
            Self::Match => "`match`",
            Self::Default => "`default`",
            Self::Echo => "`echo`",
            Self::True => "`true`",
            Self::False => "`false`",
            Self::Null => "`null`",
            Self::LParen => "`(`",
            Self::RParen => "`)`",
            Self::LBrace => "`{`",
            Self::RBrace => "`}`",
            Self::LBracket => "`[`",
            Self::RBracket => "`]`",
            Self::Less => "`<`",
            Self::LessEqual => "`<=`",
            Self::Greater => "`>`",
            Self::GreaterEqual => "`>=`",
            Self::Colon => "`:`",
            Self::Semicolon => "`;`",
            Self::Comma => "`,`",
            Self::Question => "`?`",
            Self::QuestionQuestion => "`??`",
            Self::Plus => "`+`",
            Self::Minus => "`-`",
            Self::Star => "`*`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::Dot => "`.`",
            Self::Ellipsis => "`...`",
            Self::Equal => "`=`",
            Self::EqualEqual => "`==`",
            Self::StrictEqual => "`===`",
            Self::StrictNotEqual => "`!==`",
            Self::Bang => "`!`",
            Self::BangEqual => "`!=`",
            Self::AndAnd => "`&&`",
            Self::OrOr => "`||`",
            Self::Pipe => "`|`",
            Self::FatArrow => "`=>`",
            Self::Arrow => "`->`",
            Self::DoubleColon => "`::`",
            Self::NamespaceSeparator => "`\\`",
            Self::Eof => "end of file",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}
